app:
  host: 'http://localhost'
  port: 3000

services:
  - name: 'users'
    url: 'http://localhost:3010/graphql'

jwt:
  secret: 'secret'
  expiresIn: '6h'

apollo_key: 'service:app-nest-knv8p1:gMZOWfrZQ8RsSZTr6J3V8w'
